In [1]:
import pandas as pd

In [7]:
 source = pd.read_excel('dags/data/TRAIN_WAGON_100rows.xlsx')

In [8]:
source.shape

(100, 10)

In [9]:
 source.head()

,IDTRAIN_WAGON,IDWAGON,IDTRAIN_LOT,Num_Position,IDUtilisateur_creation,DateH_creation,IDUtilisateur_maj,DateH_maj,IDWAGON_MODELE,Top_wagon_maitre
0,138270,NaN,7138,0,31,2019-09-03 18:17:27.237,0,NaN,1,0
1,138271,NaN,7138,1,31,2019-09-03 18:17:27.243,0,NaN,2,0
2,138272,NaN,7138,2,31,2019-09-03 18:17:27.247,0,NaN,2,0
3,138273,NaN,7138,3,31,2019-09-03 18:17:27.253,0,NaN,2,0
4,138274,NaN,7138,4,31,2019-09-03 18:17:27.260,0,NaN,2,0

In [11]:
target_fields = source.columns.tolist()
target_fields

['IDTRAIN_WAGON',
 'IDWAGON',
 'IDTRAIN_LOT',
 'Num_Position',
 'IDUtilisateur_creation',
 'DateH_creation',
 'IDUtilisateur_maj',
 'DateH_maj',
 'IDWAGON_MODELE',
 'Top_wagon_maitre']

In [6]:
rows = source.values.tolist()
rows

[[138270, nan, 7138, 0, 31, '2019-09-03 18:17:27.237', 0, nan, 1, 0],
 [138271, nan, 7138, 1, 31, '2019-09-03 18:17:27.243', 0, nan, 2, 0],
 [138272, nan, 7138, 2, 31, '2019-09-03 18:17:27.247', 0, nan, 2, 0],
 [138273, nan, 7138, 3, 31, '2019-09-03 18:17:27.253', 0, nan, 2, 0],
 [138274, nan, 7138, 4, 31, '2019-09-03 18:17:27.260', 0, nan, 2, 0],
 [138275, nan, 7138, 5, 31, '2019-09-03 18:17:27.267', 0, nan, 2, 0],
 [138276, nan, 7138, 6, 31, '2019-09-03 18:17:27.270', 0, nan, 2, 0],
 [138277, nan, 7138, 7, 31, '2019-09-03 18:17:27.277', 0, nan, 2, 0],
 [138278, nan, 7138, 8, 31, '2019-09-03 18:17:27.283', 0, nan, 2, 0],
 [138279, nan, 7138, 9, 31, '2019-09-03 18:17:27.290', 0, nan, 2, 0],
 [138280, nan, 7138, 10, 31, '2019-09-03 18:17:27.297', 0, nan, 2, 0],
 [138281, nan, 7138, 11, 31, '2019-09-03 18:17:27.300', 0, nan, 2, 0],
 [138282, nan, 7138, 12, 31, '2019-09-03 18:17:27.307', 0, nan, 2, 0],
 [138283, nan, 7138, 13, 31, '2019-09-03 18:17:27.313', 0, nan, 2, 0],
 [138284, nan, 7138, 14, 31, '2019-09-03 18:17:27.320', 0, nan, 2, 0],
 [138285, nan, 7138, 15, 31, '2019-09-03 18:17:27.323', 0, nan, 2, 0],
 [138286, nan, 7138, 16, 31, '2019-09-03 18:17:27.330', 0, nan, 2, 0],
 [138287, nan, 7138, 17, 31, '2019-09-03 18:17:27.333', 0, nan, 2, 0],
 [138288, nan, 7138, 18, 31, '2019-09-03 18:17:27.340', 0, nan, 2, 0],
 [138289, nan, 7138, 19, 31, '2019-09-03 18:17:27.347', 0, nan, 2, 0],
 [138290, nan, 7138, 20, 31, '2019-09-03 18:17:27.350', 0, nan, 2, 0],
 [138291, nan, 7138, 21, 31, '2019-09-03 18:17:27.357', 0, nan, 2, 0],
 [138292, nan, 7139, 0, 31, '2019-09-03 18:17:27.570', 0, nan, 1, 0],
 [138293, nan, 7139, 1, 31, '2019-09-03 18:17:27.577', 0, nan, 2, 0],
 [138294, nan, 7139, 2, 31, '2019-09-03 18:17:27.583', 0, nan, 2, 0],
 [138295, nan, 7139, 3, 31, '2019-09-03 18:17:27.587', 0, nan, 2, 0],
 [138296, nan, 7139, 4, 31, '2019-09-03 18:17:27.593', 0, nan, 2, 0],
 [138297, nan, 7139, 5, 31, '2019-09-03 18:17:27.600', 0, nan, 2, 0],
 [138298, nan, 7139, 6, 31, '2019-09-03 18:17:27.603', 0, nan, 2, 0],
 [138299, nan, 7139, 7, 31, '2019-09-03 18:17:27.610', 0, nan, 2, 0],
 [138300, nan, 7139, 8, 31, '2019-09-03 18:17:27.613', 0, nan, 2, 0],
 [138301, nan, 7139, 9, 31, '2019-09-03 18:17:27.620', 0, nan, 2, 0],
 [138302, nan, 7139, 10, 31, '2019-09-03 18:17:27.623', 0, nan, 2, 0],
 [138303, nan, 7139, 11, 31, '2019-09-03 18:17:27.630', 0, nan, 2, 0],
 [138304, nan, 7139, 12, 31, '2019-09-03 18:17:27.637', 0, nan, 2, 0],
 [138305, nan, 7139, 13, 31, '2019-09-03 18:17:27.640', 0, nan, 2, 0],
 [138306, nan, 7139, 14, 31, '2019-09-03 18:17:27.647', 0, nan, 2, 0],
 [138307, nan, 7139, 15, 31, '2019-09-03 18:17:27.657', 0, nan, 2, 0],
 [138308, nan, 7139, 16, 31, '2019-09-03 18:17:27.660', 0, nan, 2, 0],
 [138309, nan, 7139, 17, 31, '2019-09-03 18:17:27.667', 0, nan, 2, 0],
 [138310, nan, 7139, 18, 31, '2019-09-03 18:17:27.673', 0, nan, 2, 0],
 [138311, nan, 7139, 19, 31, '2019-09-03 18:17:27.680', 0, nan, 2, 0],
 [138312, nan, 7139, 20, 31, '2019-09-03 18:17:27.687', 0, nan, 2, 0],
 [138313, nan, 7139, 21, 31, '2019-09-03 18:17:27.693', 0, nan, 2, 0],
 [138314, nan, 7140, 0, 31, '2019-09-03 18:17:27.903', 0, nan, 1, 0],
 [138315, nan, 7140, 1, 31, '2019-09-03 18:17:27.907', 0, nan, 2, 0],
 [138316, nan, 7140, 2, 31, '2019-09-03 18:17:27.913', 0, nan, 2, 0],
 [138317, nan, 7140, 3, 31, '2019-09-03 18:17:27.920', 0, nan, 2, 0],
 [138318, nan, 7140, 4, 31, '2019-09-03 18:17:27.927', 0, nan, 2, 0],
 [138319, nan, 7140, 5, 31, '2019-09-03 18:17:27.933', 0, nan, 2, 0],
 [138320, nan, 7140, 6, 31, '2019-09-03 18:17:27.937', 0, nan, 2, 0],
 [138321, nan, 7140, 7, 31, '2019-09-03 18:17:27.943', 0, nan, 2, 0],
 [138322, nan, 7140, 8, 31, '2019-09-03 18:17:27.950', 0, nan, 2, 0],
 [138323, nan, 7140, 9, 31, '2019-09-03 18:17:27.953', 0, nan, 2, 0],
 [138324, nan, 7140, 10, 31, '2019-09-03 18:17:27.960', 0, nan, 2, 0],
 [138325, nan, 7140, 11, 31, '2019-09-03 18:17:27.963', 0, nan, 2, 0],
 [138326, nan, 7140, 12, 31, '2019-09-03 18:17:27.970', 0, nan, 2, 0],
 [138327, nan, 7140, 13, 31, '2019-09-03 18:17:27.973', 0, nan, 2, 0],
 [138328, nan, 7140, 14, 31, '2019-09-03 18:17:27.980', 0, nan, 2, 0],
 [138329, nan, 7140, 15, 31, '2019-09-03 18:17:27.987', 0, nan, 2, 0],
 [138330, nan, 7140, 16, 31, '2019-09-03 18:17:27.993', 0, nan, 2, 0],
 [138331, nan, 7140, 17, 31, '2019-09-03 18:17:27.997', 0, nan, 2, 0],
 [138332, nan, 7140, 18, 31, '2019-09-03 18:17:28.003', 0, nan, 2, 0],
 [138333, nan, 7140, 19, 31, '2019-09-03 18:17:28.010', 0, nan, 2, 0],
 [138334, nan, 7140, 20, 31, '2019-09-03 18:17:28.017', 0, nan, 2, 0],
 [138335, nan, 7140, 21, 31, '2019-09-03 18:17:28.023', 0, nan, 2, 0],
 [138336, nan, 7141, 0, 31, '2019-09-03 18:17:28.227', 0, nan, 1, 0],
 [138337, 60.0, 7141, 1, 31, '2019-09-03 18:17:29.233', 0, nan, 2, 0],
 [138338, 41.0, 7141, 2, 31, '2019-09-03 18:17:29.240', 0, nan, 2, 0],
 [138339, 357.0, 7141, 3, 31, '2019-09-03 18:17:29.247', 0, nan, 2, 0],
 [138340, 356.0, 7141, 4, 31, '2019-09-03 18:17:29.253', 0, nan, 2, 0],
 [138341, 66.0, 7141, 5, 31, '2019-09-03 18:17:29.257', 0, nan, 2, 0],
 [138342, 355.0, 7141, 6, 31, '2019-09-03 18:17:29.263', 0, nan, 2, 0],
 [138343, 354.0, 7141, 7, 31, '2019-09-03 18:17:29.270', 0, nan, 2, 0],
 [138344, 288.0, 7141, 8, 31, '2019-09-03 18:17:29.277', 0, nan, 2, 0],
 [138345, 287.0, 7141, 9, 31, '2019-09-03 18:17:29.283', 0, nan, 2, 0],
 [138346, 87.0, 7141, 10, 31, '2019-09-03 18:17:29.287', 0, nan, 2, 0],
 [138347, 21.0, 7141, 11, 31, '2019-09-03 18:17:29.293', 0, nan, 2, 0],
 [138348, 86.0, 7141, 12, 31, '2019-09-03 18:17:29.297', 0, nan, 2, 0],
 [138349, 290.0, 7141, 13, 31, '2019-09-03 18:17:29.303', 0, nan, 2, 0],
 [138350, 353.0, 7141, 14, 31, '2019-09-03 18:17:29.307', 0, nan, 2, 0],
 [138351, 289.0, 7141, 15, 31, '2019-09-03 18:17:29.313', 0, nan, 2, 0],
 [138352, 58.0, 7141, 16, 31, '2019-09-03 18:17:29.317', 0, nan, 2, 0],
 [138353, 68.0, 7141, 17, 31, '2019-09-03 18:17:29.320', 0, nan, 2, 0],
 [138354, 285.0, 7141, 18, 31, '2019-09-03 18:17:29.327', 0, nan, 2, 0],
 [138355, 284.0, 7141, 19, 31, '2019-09-03 18:17:29.333', 0, nan, 2, 0],
 [138356, 80.0, 7141, 20, 31, '2019-09-03 18:17:29.337', 0, nan, 2, 0],
 [138357, 45.0, 7141, 21, 31, '2019-09-03 18:17:29.340', 0, nan, 2, 0],
 [138358, nan, 7142, 0, 31, '2019-09-03 18:17:28.557', 0, nan, 1, 0],
 [138359, nan, 7142, 1, 31, '2019-09-03 18:17:28.563', 0, nan, 2, 0],
 [138360, nan, 7142, 2, 31, '2019-09-03 18:17:28.570', 0, nan, 2, 0],
 [138361, nan, 7142, 3, 31, '2019-09-03 18:17:28.573', 0, nan, 2, 0],
 [138362, nan, 7142, 4, 31, '2019-09-03 18:17:28.580', 0, nan, 2, 0],
 [138363, nan, 7142, 5, 31, '2019-09-03 18:17:28.587', 0, nan, 2, 0],
 [138364, nan, 7142, 6, 31, '2019-09-03 18:17:28.590', 0, nan, 2, 0],
 [138365, nan, 7142, 7, 31, '2019-09-03 18:17:28.597', 0, nan, 2, 0],
 [138366, nan, 7142, 8, 31, '2019-09-03 18:17:28.600', 0, nan, 2, 0],
 [138367, nan, 7142, 9, 31, '2019-09-03 18:17:28.607', 0, nan, 2, 0],
 [138368, nan, 7142, 10, 31, '2019-09-03 18:17:28.610', 0, nan, 2, 0],
 [138369, nan, 7142, 11, 31, '2019-09-03 18:17:28.617', 0, nan, 2, 0]]